// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASjPq2g1cHv8H20aF9gDpCQvlmgDq_BiA',
    appId: '1:784826171005:web:7cd240f56728e1ac45bb14',
    messagingSenderId: '784826171005',
    projectId: 'sasacation-25b57',
    authDomain: 'sasacation-25b57.firebaseapp.com',
    storageBucket: 'sasacation-25b57.firebasestorage.app',
    measurementId: 'G-6990VX6J9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLHtumTlKSUjh2lpVIb3kqWm5t44dLThU',
    appId: '1:784826171005:android:1905d854ce6e079345bb14',
    messagingSenderId: '784826171005',
    projectId: 'sasacation-25b57',
    storageBucket: 'sasacation-25b57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl0OH2F2PBeDAb8cVfbzAEgrMvekTbY5c',
    appId: '1:784826171005:ios:1803772e1cc1491f45bb14',
    messagingSenderId: '784826171005',
    projectId: 'sasacation-25b57',
    storageBucket: 'sasacation-25b57.firebasestorage.app',
    iosBundleId: 'com.example.sasacation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl0OH2F2PBeDAb8cVfbzAEgrMvekTbY5c',
    appId: '1:784826171005:ios:1803772e1cc1491f45bb14',
    messagingSenderId: '784826171005',
    projectId: 'sasacation-25b57',
    storageBucket: 'sasacation-25b57.firebasestorage.app',
    iosBundleId: 'com.example.sasacation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASjPq2g1cHv8H20aF9gDpCQvlmgDq_BiA',
    appId: '1:784826171005:web:490df160de418b1345bb14',
    messagingSenderId: '784826171005',
    projectId: 'sasacation-25b57',
    authDomain: 'sasacation-25b57.firebaseapp.com',
    storageBucket: 'sasacation-25b57.firebasestorage.app',
    measurementId: 'G-R39CJ518E3',
  );
}
